apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::000000000000:role/eksctl-automatically-created-role
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-01T00:01:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1234"
  uid: some-long-uid
